### ISSUE TITLE
b831e96c6a2f0dc1768012f3bbf78ffef3701886LF-yx7egtyrkvapiVersion: apps/v1  kind: Deployment  metadata:    name: my-nginx  spec:    selector:      matchLabels:        run: my-nginx    replicas: 2    template:      metadata:        labels:          run: my-nginx      spec:        containers:        - name: my-nginx          image: nginx          ports:          - containerPort: 80

### ISSUE THREAD

**Issue by BEGA-EX** [except-app/except.chat#1]
apiVersion: apps/v1

kind: Deployment

metadata:

  name: my-nginx

spec:

  selector:

    matchLabels:

      run: my-nginx

  replicas: 2

  template:

    metadata:

      labels:

        run: my-nginx

    spec:

      containers:

      - name: my-nginx

        image: nginx

        ports:

        - containerPort: 80

b831e96c6a2f0dc1768012f3bbf78ffef3701886apiVersion: apps/v1

kind: Deployment

metadata:

  name: my-nginx

spec:

  selector:

    matchLabels:

      run: my-nginx

  replicas: 2

  template:

    metadata:

      labels:

        run: my-nginx

    spec:

      containers:

      - name: my-nginx

        image: nginx

        ports:

        - containerPort: 80

**Comment by radufarcas10** [comment]
Dude, are you seriously that stupid?

**Comment by radufarcas10** [comment]
Some stupid dude opened this for no freaking reason
